/**
 * Fake colony for the public Vercel demo. Nothing here reads a real disk — this deployment
 * has no local machine to read from — so every thread is invented, but shaped exactly like
 * the real ones a harness adapter hands back, covering every astronaut state at once.
 */
const MIN = 60 * 1000
const HOUR = 60 * MIN
const DAY = 24 * HOUR

const ago = (ms) => Date.now() - ms

export function demoThreads() {
  const now = Date.now()
  return [
    {
      id: 'demo:claude-code:growth-1',
      harness: 'claude-code',
      harnessName: 'Claude Code',
      title: 'Wire up the new pricing table',
      preview: 'Swap the old three-tier card grid for the new comparison layout from Figma',
      project: 'growth-dashboard',
      projectPath: '/Users/demo/code/growth-dashboard',
      worktree: '',
      cwd: '/Users/demo/code/growth-dashboard',
      gitBranch: 'main',
      model: 'claude-sonnet-5',
      effort: 'high',
      createdAt: ago(3 * HOUR),
      lastActivityAt: ago(8 * 1000),
      lastFocusedAt: ago(2 * HOUR),
      running: true,
      unread: false,
      hasError: false,
      starred: false,
      routine: '',
      prState: '',
      archived: false,
      hasTranscript: true,
      sizeBytes: 210_000,
      canOpen: true,
      source: 'cli',
      ref: { demo: true },
    },
    {
      id: 'demo:claude-code:growth-2',
      harness: 'claude-code',
      harnessName: 'Claude Code',
      title: 'Investigate the flaky checkout redirect test',
      preview: 'The Playwright run fails maybe one time in five — looks timing-related',
      project: 'growth-dashboard',
      projectPath: '/Users/demo/code/growth-dashboard',
      worktree: 'feature-onboarding',
      cwd: '/Users/demo/code/growth-dashboard/.claude/worktrees/feature-onboarding',
      gitBranch: 'feature/onboarding-v2',
      model: 'claude-sonnet-5',
      effort: 'medium',
      createdAt: ago(6 * HOUR),
      lastActivityAt: ago(14 * MIN),
      lastFocusedAt: ago(4 * HOUR),
      running: false,
      unread: true,
      hasError: false,
      starred: false,
      routine: '',
      prState: '',
      archived: false,
      hasTranscript: true,
      sizeBytes: 96_000,
      canOpen: true,
      source: 'cli',
      ref: { demo: true },
    },
    {
      id: 'demo:codex:checkout-1',
      harness: 'codex',
      harnessName: 'Codex',
      title: 'Migrate the payments webhook to the new signing scheme',
      preview: 'Stripe is deprecating the old signature header on the 30th',
      project: 'checkout-service',
      projectPath: '/Users/demo/code/checkout-service',
      worktree: '',
      cwd: '/Users/demo/code/checkout-service',
      gitBranch: 'main',
      model: 'gpt-5.3-codex',
      effort: 'high',
      createdAt: ago(1 * DAY),
      lastActivityAt: ago(40 * MIN),
      lastFocusedAt: ago(5 * HOUR),
      running: false,
      unread: false,
      hasError: true,
      starred: false,
      routine: '',
      prState: '',
      archived: false,
      hasTranscript: true,
      sizeBytes: 58_000,
      canOpen: true,
      source: 'cli',
      ref: { demo: true },
    },
    {
      id: 'demo:codex:checkout-2',
      harness: 'codex',
      harnessName: 'Codex',
      title: 'Add retry backoff to the inventory sync job',
      preview: 'Exponential backoff, capped at five attempts, logged to the ops channel',
      project: 'checkout-service',
      projectPath: '/Users/demo/code/checkout-service',
      worktree: '',
      cwd: '/Users/demo/code/checkout-service',
      gitBranch: 'fix/inventory-retries',
      model: 'gpt-5.3-codex',
      effort: 'medium',
      createdAt: ago(2 * DAY),
      lastActivityAt: ago(3 * HOUR),
      lastFocusedAt: ago(3 * HOUR),
      running: false,
      unread: false,
      hasError: false,
      starred: false,
      routine: '',
      prState: 'merged',
      archived: false,
      hasTranscript: true,
      sizeBytes: 132_000,
      canOpen: true,
      source: 'cli',
      ref: { demo: true },
    },
    {
      id: 'demo:cursor:docs-1',
      harness: 'cursor',
      harnessName: 'Cursor',
      title: 'what does the deploy script actually check before pushing?',
      preview: 'what does the deploy script actually check before pushing?',
      project: 'docs-site',
      projectPath: '/Users/demo/code/docs-site',
      worktree: '',
      cwd: '/Users/demo/code/docs-site',
      gitBranch: 'main',
      model: '',
      effort: '',
      createdAt: ago(5 * DAY),
      lastActivityAt: ago(4 * DAY),
      lastFocusedAt: ago(4 * DAY),
      running: false,
      unread: false,
      hasError: false,
      starred: false,
      routine: '',
      prState: '',
      archived: false,
      hasTranscript: true,
      sizeBytes: 21_000,
      canOpen: true,
      source: 'cli',
      ref: { demo: true },
    },
    {
      id: 'demo:cursor:docs-2',
      harness: 'cursor',
      harnessName: 'Cursor',
      title: 'Rewrite the self-hosting page for the new config format',
      preview: 'The old env-var table is out of date since the v2 config rewrite',
      project: 'docs-site',
      projectPath: '/Users/demo/code/docs-site',
      worktree: '',
      cwd: '/Users/demo/code/docs-site',
      gitBranch: 'docs/self-hosting-v2',
      model: '',
      effort: '',
      createdAt: ago(9 * HOUR),
      lastActivityAt: ago(1 * HOUR),
      lastFocusedAt: ago(1 * HOUR),
      running: false,
      unread: false,
      hasError: false,
      starred: false,
      routine: '',
      prState: '',
      archived: false,
      hasTranscript: true,
      sizeBytes: 44_000,
      canOpen: true,
      source: 'cli',
      ref: { demo: true },
    },
    {
      id: 'demo:codex:internal-1',
      harness: 'codex',
      harnessName: 'Codex',
      title: 'Add a CSV export to the admin usage report',
      preview: 'Finance wants the same numbers the dashboard shows, but downloadable',
      project: 'internal-tools',
      projectPath: '/Users/demo/code/internal-tools',
      worktree: '',
      cwd: '/Users/demo/code/internal-tools',
      gitBranch: 'main',
      model: 'gpt-5.3-codex',
      effort: 'low',
      createdAt: ago(30 * MIN),
      lastActivityAt: ago(3 * MIN),
      lastFocusedAt: ago(20 * MIN),
      running: false,
      unread: true,
      hasError: false,
      starred: false,
      routine: '',
      prState: '',
      archived: false,
      hasTranscript: true,
      sizeBytes: 9_000,
      canOpen: true,
      source: 'cli',
      ref: { demo: true },
    },
  ]
}

export function demoHarnesses() {
  return [
    { id: 'claude-code', name: 'Claude Code', detected: true, error: '' },
    { id: 'codex', name: 'Codex', detected: true, error: '' },
    { id: 'cursor', name: 'Cursor', detected: true, error: '' },
  ]
}

export const DEMO_MESSAGE =
  'This is a live demo with sample data — clone the repo and run it locally to see your own agent threads.'
